# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# jobs:
#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.build-publish.outputs.page_url }}
#     runs-on: ubuntu-latest
#     steps:
#     - name: Setup pnpm
#       uses: pnpm/action-setup@v2.0.0
#       with:
#         version: 8.5.1 # specify the pnpm version you need
#     - id: build-publish
#       uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
#       with:
#         path: storybook-static
#         install_command: pnpm install
#         build_command: pnpm run build-storybook
